apiVersion: apps/v1
kind: Deployment
metadata:
  name: leads
  labels:
    app: leads
spec:
  replicas: 1
  selector:
    matchLabels:
      name: leads
  template:
    metadata:
      labels:
        name: leads
    spec:
      containers:
        - name: leads
          image: khabdrick/leads:ver1
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: POSTGRES_USER
              value: "khabdrick"
            - name: POSTGRES_PASSWORD
              value: "secure-password"
            - name: POSTGRES_DB
              value: 'leads'
            - name: DATABASE_URL
              value: psql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@postgres:5432/$(POSTGRES_DB)


---
# START Service
apiVersion: v1
kind: Service
metadata:
  name: leads
  labels:
    app: leads
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8000
  selector:
    name: leads
# END SERVICE